### ISSUE TITLE
Failed to generate API key

### ISSUE THREAD

**Issue by phil-d-wilson** [balenablocks/dashboard#12]
There is an edge case which can cause `dashboard` to fail to generate a dashboard, due to a failure to create an API key.

## Repro steps
* Deploy an app using `dashboard`
* Move a device from an app already using `dashboard`

## Expected behaviour
The device moves to the new app, downloads the containers and generates a dashboard

## Actual behaviour
```
Starting dashboard sync, checking APIs...
Could not generate API key (this is bad)
APIs available, proceeding...
Synchronizing dashboard for mqtt_consumer
Traceback (most recent call last):
  File "/usr/src/app/update-dashboards.py", line 17, in <module>
    grafana_dash_gen.sync_dashboard(measurement)
  File "/usr/src/app/grafana_dash_gen.py", line 99, in sync_dashboard
    if self.load_existing_dashboard(data['name']):
  File "/usr/src/app/grafana_dash_gen.py", line 156, in load_existing_dashboard
    req.add_header('Authorization', 'Bearer ' + self.apikey)
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by phil-d-wilson** [comment]
After some debugging, I added a print line to show the details of the exceptions caught on this line:

```python
except (urllib.error.HTTPError, urllib.error.URLError):
                print('Could not generate API key (this is bad)')
                return False
```

For this edge case the HTTP error is `HTTP Error 409: Conflict`
I think this comes from [here](https://github.com/grafana/grafana/blob/1ac02390e24e51b85eab485ec1db1224e2c004b0/pkg/api/org_users.go#L41) :

```go
if errors.Is(err, models.ErrOrgUserAlreadyAdded) {
			return JSON(409, util.DynMap{
				"message": "User is already member of this organization",
				"userId":  cmd.UserId,
			})
		}
```
which would suggest we can handle a 409 error, and try to retrieve the API key rather than create it - or delete this existing user and recreate.
